/** Structured application error codes (PRD §21). Returned over IPC; translated in renderer. */
export const AppErrorCode = {
  // VAL — validation
  VAL_MASTER_NO: 'VAL_MASTER_NO',
  VAL_MASTER_VALUE_REQUIRED: 'VAL_MASTER_VALUE_REQUIRED',
  VAL_MASTER_VALUE: 'VAL_MASTER_VALUE',
  VAL_MASTER_VALUE_EMPTY: 'VAL_MASTER_VALUE_EMPTY',
  VAL_MASTER_VALUE_LENGTH: 'VAL_MASTER_VALUE_LENGTH',
  VAL_MASTER_VALUE_LENGTH_BULK: 'VAL_MASTER_VALUE_LENGTH_BULK',
  VAL_MASTER_DUP: 'VAL_MASTER_DUP',
  VAL_MASTER_NO_INVALID: 'VAL_MASTER_NO_INVALID',
  VAL_MASTER_NOT_FOUND: 'VAL_MASTER_NOT_FOUND',
  VAL_CODE_REQUIRED: 'VAL_CODE_REQUIRED',
  VAL_CODE_TYPE_REQUIRED: 'VAL_CODE_TYPE_REQUIRED',
  VAL_CODE_DUP: 'VAL_CODE_DUP',
  VAL_CODE_NOT_FOUND: 'VAL_CODE_NOT_FOUND',
  VAL_CODE_VALUE_CODE_REQUIRED: 'VAL_CODE_VALUE_CODE_REQUIRED',
  VAL_CODE_VALUE_VALUE_REQUIRED: 'VAL_CODE_VALUE_VALUE_REQUIRED',
  VAL_CODE_VALUE_LENGTH: 'VAL_CODE_VALUE_LENGTH',
  VAL_CODE_VALUE_NOT_FOUND: 'VAL_CODE_VALUE_NOT_FOUND',
  VAL_EXPERIMENT_NOT_FOUND: 'VAL_EXPERIMENT_NOT_FOUND',

  // DB — database
  DB_NOT_INIT: 'DB_NOT_INIT',
  DB_BACKUP_FAILED: 'DB_BACKUP_FAILED',
  DB_RESTORE_FAILED: 'DB_RESTORE_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  DB_GENERIC: 'DB_GENERIC',
  DB_HISTORY_SAVE_FAILED: 'DB_HISTORY_SAVE_FAILED',
  DB_STATISTICS_SAVE_FAILED: 'DB_STATISTICS_SAVE_FAILED',

  // IPC — renderer ↔ main
  IPC_UNAVAILABLE: 'IPC_UNAVAILABLE',
  IPC_TIMEOUT: 'IPC_TIMEOUT',
  IPC_ANALYSIS_FAILED: 'IPC_ANALYSIS_FAILED',
  IPC_REGRESSION_FAILED: 'IPC_REGRESSION_FAILED',
  IPC_VERIFICATION_FAILED: 'IPC_VERIFICATION_FAILED',
  IPC_HEALTH_CHECK_FAILED: 'IPC_HEALTH_CHECK_FAILED',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];

const CODE_SET = new Set<string>(Object.values(AppErrorCode));

export function isAppErrorCode(value: string): value is AppErrorCode {
  return CODE_SET.has(value);
}

/** Prefix a row/context label before an error code, e.g. `Master 01: VAL_MASTER_NO`. */
export function contextError(context: string, code: AppErrorCode): string {
  return `${context}: ${code}`;
}
