export {
  analyzeMasterValue,
  buildRuns,
  calcRate,
  classifyChar,
  classifyDigit,
  createEmptyAnalysisResult,
  extractDigits,
  extractSidePatterns,
  matchCompositeComma,
  matchCompositePlus,
  splitLowHighCounts,
  toClassSequence,
  COMPOSITE_COMMA_RULES,
  COMPOSITE_PLUS_RULES,
  type AnalysisResult,
  type ClassRun,
  type CompositeCommaRule,
  type CompositePlusRule,
  type DigitClass,
  type SidePatterns,
} from './utils/analysisEngine';
