/** Electron DB 초기 시드 — CODE 등록 화면 기준 31건 */
export const SEED_CODES = [
  { code: '01', type: '저점', description: '저점,저점' },
  { code: '02', type: '저점', description: '저점,고점' },
  { code: '03', type: '저점', description: '고점,저점' },
  { code: '04', type: '저점', description: '고점,고점' },
  { code: '05', type: '저점', description: '저점,저점,저점' },
  { code: '06', type: '저점', description: '저점,저점,고점' },
  { code: '07', type: '저점', description: '저점,고점,저점' },
  { code: '08', type: '저점', description: '고점,저점,저점' },
  { code: '09', type: '저점', description: '고점,고점,저점' },
  { code: '10', type: '고점', description: '저점,고점' },
  { code: '12', type: '저점', description: '저점,고점,고점' },
  { code: '13', type: '저점', description: '고점,저점,고점' },
  { code: '01234', type: '저점', description: '저점,저점,고점,고점,저점' },
  { code: '14', type: '저점', description: '저점,고점,고점,저점' },
  { code: '15', type: '저점', description: '고점,저점,저점,고점' },
  { code: '20', type: '고점', description: '저점,고점' },
  { code: '23', type: '고점', description: '고점,고점' },
  { code: '24', type: '고점', description: '고점,저점' },
  { code: '25', type: '고점', description: '저점,저점,고점,고점' },
  { code: '30', type: '고점', description: '저점,고점,고점' },
  { code: '32', type: '고점', description: '고점,저점,고점' },
  { code: '34', type: '고점', description: '고점,고점,저점' },
  { code: '35', type: '고점', description: '고점,고점,고점,저점' },
  { code: '40', type: '고점', description: '저점,저점,고점' },
  { code: '42', type: '고점', description: '저점,고점,저점' },
  { code: '43', type: '고점', description: '고점,저점,저점' },
  { code: '45', type: '고점', description: '저점,고점,고점,저점' },
  { code: '234', type: '저점', description: '저점,고점,저점' },
  { code: '324', type: '고점', description: '고점,저점,고점' },
  { code: '423', type: '고점', description: '저점,고점,고점,저점' },
  { code: '23401', type: '저점', description: '고점,고점,저점,저점,고점' },
] as const;
